DROP INDEX IF EXISTS uq_active_task_locks_folder;
DROP INDEX IF EXISTS uq_active_task_locks_run;
DROP INDEX IF EXISTS idx_job_queue_priority;
DROP INDEX IF EXISTS idx_file_attempts_status;
DROP INDEX IF EXISTS idx_file_attempts_run_file;
DROP INDEX IF EXISTS idx_run_files_final;
DROP INDEX IF EXISTS idx_sync_runs_status;
DROP INDEX IF EXISTS idx_sync_runs_task;
DROP TABLE IF EXISTS job_queue;
DROP TABLE IF EXISTS file_attempts;
DROP TABLE IF EXISTS sync_runs;
DROP TABLE IF EXISTS system_settings;
ALTER TABLE active_task_locks DROP COLUMN heartbeat_at;
ALTER TABLE active_task_locks DROP COLUMN run_status;
ALTER TABLE active_task_locks DROP COLUMN run_id;
ALTER TABLE run_files DROP COLUMN ordinal;
ALTER TABLE sync_files DROP COLUMN observed_modified_at;
ALTER TABLE sync_files DROP COLUMN observed_size;
ALTER TABLE sync_files DROP COLUMN pending_remote_doc_id;
