// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function CleanupMinerUArtifacts():Promise<api.MinerUArtifactCleanupResultDTO>;

export function ConfigureMaxKB(arg1:api.MaxKBConfigDTO):Promise<void>;

export function ConfigureMinerU(arg1:api.MinerUConfigDTO):Promise<void>;

export function ConfigureMinerUArtifactSettings(arg1:api.MinerUArtifactSettingsDTO):Promise<void>;

export function CreateFolder(arg1:api.CreateFolderRequest):Promise<api.FolderDTO>;

export function CreateKnowledgeBase(arg1:api.CreateKnowledgeBaseDTO):Promise<api.KnowledgeBaseDTO>;

export function CreateTask(arg1:string,arg2:string):Promise<api.TaskDTO>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DetectChanges(arg1:string):Promise<string>;

export function DisableTask(arg1:string):Promise<void>;

export function EnableTask(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetDataDirectory():Promise<string>;

export function GetFileStats(arg1:string):Promise<api.FileStatsDTO>;

export function GetFolder(arg1:string):Promise<api.FolderDTO>;

export function GetMaxKBConfig():Promise<api.MaxKBConfigDTO>;

export function GetMinerUArtifactSettings():Promise<api.MinerUArtifactSettingsDTO>;

export function GetMinerUConfig():Promise<api.MinerUConfigDTO>;

export function GetQueueStats():Promise<api.QueueStatsDTO>;

export function GetRunFiles(arg1:string):Promise<Array<api.RunFileDTO>>;

export function GetTask(arg1:string):Promise<api.TaskDTO>;

export function Greet(arg1:string):Promise<string>;

export function ListEmbeddingModels(arg1:string):Promise<Array<api.EmbeddingModelDTO>>;

export function ListFiles(arg1:string):Promise<Array<api.FileDTO>>;

export function ListFilesByStatus(arg1:string,arg2:string):Promise<Array<api.FileDTO>>;

export function ListFolders():Promise<Array<api.FolderDTO>>;

export function ListKnowledgeBases(arg1:string):Promise<Array<api.KnowledgeBaseDTO>>;

export function ListKnowledgeFolders(arg1:string):Promise<Array<api.KnowledgeFolderDTO>>;

export function ListPendingFiles(arg1:string):Promise<Array<api.FileDTO>>;

export function ListReconcileRequired():Promise<Array<api.ReconcileDTO>>;

export function ListRunningTasks():Promise<Array<api.TaskDTO>>;

export function ListTasks(arg1:string,arg2:number):Promise<Array<api.TaskDTO>>;

export function ListWorkspaces():Promise<Array<api.WorkspaceDTO>>;

export function PauseTask(arg1:string):Promise<void>;

export function PreviewMatch(arg1:api.PreviewMatchRequest):Promise<api.PreviewMatchResult>;

export function ResolveReconcile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResumeTask(arg1:string):Promise<void>;

export function RetryFailedTask(arg1:string):Promise<api.TaskDTO>;

export function ScanFolder(arg1:string):Promise<api.ScanResultDTO>;

export function SelectDirectory():Promise<string>;

export function StopTask(arg1:string):Promise<void>;

export function TestMaxKBConnection(arg1:api.MaxKBConfigDTO):Promise<string>;

export function TestMinerUConnection(arg1:api.MinerUConfigDTO):Promise<void>;

export function UpdateFolder(arg1:string,arg2:api.CreateFolderRequest):Promise<api.FolderDTO>;

export function ValidateCronExpression(arg1:string):Promise<void>;
