// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupMinerUArtifacts() {
  return window['go']['main']['App']['CleanupMinerUArtifacts']();
}

export function ConfigureMaxKB(arg1) {
  return window['go']['main']['App']['ConfigureMaxKB'](arg1);
}

export function ConfigureMinerU(arg1) {
  return window['go']['main']['App']['ConfigureMinerU'](arg1);
}

export function ConfigureMinerUArtifactSettings(arg1) {
  return window['go']['main']['App']['ConfigureMinerUArtifactSettings'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateKnowledgeBase(arg1) {
  return window['go']['main']['App']['CreateKnowledgeBase'](arg1);
}

export function CreateTask(arg1, arg2) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DetectChanges(arg1) {
  return window['go']['main']['App']['DetectChanges'](arg1);
}

export function DisableTask(arg1) {
  return window['go']['main']['App']['DisableTask'](arg1);
}

export function EnableTask(arg1) {
  return window['go']['main']['App']['EnableTask'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDataDirectory() {
  return window['go']['main']['App']['GetDataDirectory']();
}

export function GetFileStats(arg1) {
  return window['go']['main']['App']['GetFileStats'](arg1);
}

export function GetFolder(arg1) {
  return window['go']['main']['App']['GetFolder'](arg1);
}

export function GetMaxKBConfig() {
  return window['go']['main']['App']['GetMaxKBConfig']();
}

export function GetMinerUArtifactSettings() {
  return window['go']['main']['App']['GetMinerUArtifactSettings']();
}

export function GetMinerUConfig() {
  return window['go']['main']['App']['GetMinerUConfig']();
}

export function GetQueueStats() {
  return window['go']['main']['App']['GetQueueStats']();
}

export function GetRunFiles(arg1) {
  return window['go']['main']['App']['GetRunFiles'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListEmbeddingModels(arg1) {
  return window['go']['main']['App']['ListEmbeddingModels'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListFilesByStatus(arg1, arg2) {
  return window['go']['main']['App']['ListFilesByStatus'](arg1, arg2);
}

export function ListFolders() {
  return window['go']['main']['App']['ListFolders']();
}

export function ListKnowledgeBases(arg1) {
  return window['go']['main']['App']['ListKnowledgeBases'](arg1);
}

export function ListKnowledgeFolders(arg1) {
  return window['go']['main']['App']['ListKnowledgeFolders'](arg1);
}

export function ListPendingFiles(arg1) {
  return window['go']['main']['App']['ListPendingFiles'](arg1);
}

export function ListReconcileRequired() {
  return window['go']['main']['App']['ListReconcileRequired']();
}

export function ListRunningTasks() {
  return window['go']['main']['App']['ListRunningTasks']();
}

export function ListTasks(arg1, arg2) {
  return window['go']['main']['App']['ListTasks'](arg1, arg2);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function PreviewMatch(arg1) {
  return window['go']['main']['App']['PreviewMatch'](arg1);
}

export function ResolveReconcile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveReconcile'](arg1, arg2, arg3);
}

export function ResumeTask(arg1) {
  return window['go']['main']['App']['ResumeTask'](arg1);
}

export function RetryFailedTask(arg1) {
  return window['go']['main']['App']['RetryFailedTask'](arg1);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StopTask(arg1) {
  return window['go']['main']['App']['StopTask'](arg1);
}

export function TestMaxKBConnection(arg1) {
  return window['go']['main']['App']['TestMaxKBConnection'](arg1);
}

export function TestMinerUConnection(arg1) {
  return window['go']['main']['App']['TestMinerUConnection'](arg1);
}

export function UpdateFolder(arg1, arg2) {
  return window['go']['main']['App']['UpdateFolder'](arg1, arg2);
}

export function ValidateCronExpression(arg1) {
  return window['go']['main']['App']['ValidateCronExpression'](arg1);
}
